default_install_hook_types: ["pre-commit", "pre-push"]

repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint code
        entry: just lint
        language: system
        pass_filenames: false
        always_run: true
